name: Process coverage report

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: npm ci
      - run: npm run test:mocha
      - name: Upload Coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Coverage report
        uses: actions/download-artifact@v2
        with:
          name: coverage-report
      - uses: action-badges/create-orphan-branch@0.1.0
        with:
          branch-name: badges
      - name: Make Coverage Badge
        uses: action-badges/cobertura-coverage-xml-badges@0.2.1
        with:
          file-name: coverage.svg
          badge-branch: badges
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          coverage-file-name: ./coverage/cobertura-coverage.xml


